### ISSUE TITLE
Operator is started in my current namespace

### ISSUE THREAD

**Issue by jewzaam** [openshift/dedicated-admin-operator#1]
```
oc project openshift-monitoring
cd mainfests/
ls -1 | awk '{print "oc apply -R -f " $1}' | sh
```
The operator is deployed in the project I was using, not in the `openshift-dedicated-admin` namespace.

```
$ oc get pods --all-namespaces | grep dedicated 
openshift-monitoring                          dedicated-admin-operator-6bff9f7968-vwt75                             0/1     CrashLoopBackOff   4          2m10s
```

**Comment by rogbas** [comment]
Ack, will lock the namespace for the deployment and other objects under the manifests/ folder

**Comment by rogbas** [comment]
PR to lock the NSs: https://github.com/openshift/dedicated-admin-operator/pull/2

**Comment by jewzaam** [comment]
Fixed in https://github.com/openshift/dedicated-admin-operator/pull/2
