### ISSUE TITLE
Allow addition of custom namespace blacklist regex patterns

### ISSUE THREAD

**Issue by philbrookes** [openshift/dedicated-admin-operator#91]
We would like to be able to define a custom regex pattern that is blacklisted from the dedicated-admins.

Our use-case is an operator which creates namespaces which it should be the admin of, but that should not be visible to dedicated-admins.

Currently this is not possible, if we want to keep the project hidden we must create it as "openshift-.*" which means that we must create it as a namespace through the kubernetes API, as we are not allowed to create this through the openshift projects API. Creating it via the kubernetes API does not add the creator as an admin to that project.

We would like to add a new blacklist regex for a custom prefix, which these namespaces would be created with, so that we can create them through the Openshift projects API, but still remain invisible to the dedicated-admins.

If this is something you would be agreeable to, we are happy to submit the PR.

**Comment by fahlmant** [comment]
@philbrookes This operator is being replaced by the [rbac-permissions-operator](https://github.com/openshift/rbac-permissions-operator/) which uses a CRD to allow for control of the namespace regex.
